# Generated by Django 2.1.7 on 2019-08-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='hotnews',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Comments'),
        ),
    ]
