# Generated by Django 2.1.7 on 2019-08-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='tb_user',
        ),
    ]
