# Generated by Django 2.1.7 on 2019-09-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20190902_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='菜单名', max_length=48, unique=True, verbose_name='菜单名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='url', max_length=256, null=True, verbose_name='路由名称'),
        ),
    ]
